#name: Testing githib workflows
#on: push
#jobs:
#  init:
#    runs-on: ubuntu-latest
#    steps:
#      - run: echo 'hello Moussa'
#      - run: echo $HOSTNAME

#name: Démonstration CI
#
#on:
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Etape 1 - Initialisation
#        run: |
#          echo "Initialisation du pipeline..."
#          java -version
#
#      - name: Etape 2 - Récupération du code
#        uses: actions/checkout@v4
#
#      - name: Etape 3 - Build
#        run: mvn clean compile
#
#      - name: Etape 4 - Tests
#        run: mvn test
#
#      - name: Etape 5 - Packaging
#        run: mvn package -DskipTests
#
#      - name: Etape 6 - Fin du pipeline
#        run: echo "Pipeline terminé avec succès !"

name: Gestion des variables d'environnement et secrets

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  integration-continue:
    runs-on: ubuntu-latest

    # Définition des variables d'environnement pour les étapes du pipeline
    env:
      STEP1: "Workflow - Initialisation"

    steps:
      # using variables d'environnement et secrets pour les étapes du pipeline
      - name: Etape 1 - Variable workflow
        run: |
          echo "Demarrage du pipeline d'intégration continue"
          echo "STEP1= $STEP1"

      - name: Étape 2 - Variable Repository
        run: |
          echo "Variable d'environnement pour l'étape 2"
          echo "STEP2= ${{ vars.STEP2 }}"

      - name: Étape 3 - Variable Secret
        run: |
          echo "Variable d'environnement pour l'étape 3"
          echo "STEP3= ${{ secrets.STEP3 }}"
